@API_URL = http://localhost:5000/api
@FIRST_USER_ID = 019961a4-6cdc-7070-9a09-b324c92b20d3
@SECOND_USER_ID = 01996145-8243-7048-b20a-95f6f47e8033
@REPORT_ID = e008bf16-106a-40f2-9c4e-e614ef7f7a86

### Health check
GET {{API_URL}}/health
Accept: application/json

### === AUTH ===
### Check username
GET {{API_URL}}/auth/check-username?username=driver123
### Registration
POST {{API_URL}}/auth/register
Content-Type: application/json

{
  "login": "driver123456@example.com",
  "username": "driver123457",
  "password": "password1234567",
  "carMake": "Toyota",
  "carColor": "Red",
  "isAnonymous": false
}

### Login
POST {{API_URL}}/auth/login
Content-Type: application/json

{
  "login": "driver123456@example.com",
  "password": "password1234567"
}

### === USER ===
### GET User
GET {{API_URL}}/users/{{FIRST_USER_ID}}

### Update User
PUT {{API_URL}}/users/{{FIRST_USER_ID}}
Content-Type: application/json

{
  "carMake": "Toyota",
  "carColor": "Blue",
  "isAnonymous": true
}

### Delete User
DELETE {{API_URL}}/users/{{FIRST_USER_ID}}

### === RATINGS ===
### Get Ratings for User
GET {{API_URL}}/users/{{FIRST_USER_ID}}/ratings
Accept: application/json

### Rate User (Like / Dislike)
POST {{API_URL}}/users/{{FIRST_USER_ID}}/ratings
Content-Type: application/json

{
  "fromUserId": "01996145-a3e4-7108-ad0a-0d688784ec67",
  "value": 1
}

### Rate User (Dislike)
POST {{API_URL}}/users/{{FIRST_USER_ID}}/ratings
Content-Type: application/json

{
  "fromUserId": "01996145-8243-7048-b20a-95f6f47e8033",
  "value": 1
}

### === REPORTS ===
### Create Report
POST {{API_URL}}/reports
Content-Type: application/json

{
  "latitude": 50.4501,
  "longitude": 30.5234,
  "radiusMeters": 100,
  "comment": "Dangerous driving near this area",
  "ttlSeconds": 60
}

### Get All Reports
GET {{API_URL}}/reports/active
Accept: application/json

### Get Report By Id
GET {{API_URL}}/reports/{{REPORT_ID}}
Accept: application/json

### Delete Report
DELETE {{API_URL}}/reports/{{REPORT_ID}}
